apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: LoadBalancer
  selector:
    app: demo
    version: blue   # change between blue/green to switch traffic
  ports:
  - port: 80
    targetPort: 80
